name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v3
      - run: mise exec -- gleam deps download
      - run: mise exec -- gleam test
      - run: mise exec -- gleam format --check src test
      - run: mise exec -- gleam run -m gleescript
